[package]
name = "helix-macros"
version = "0.1.0"
edition = "2021"
authors = ["HelixDB Team"]
description = "Proc macros for helix-rs"
license = "AGPL-3.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "derive"] }
quote = "1.0"
proc-macro2 = "1.0"
